# Generated by Django 5.1.1 on 2024-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
