# Generated by Django 5.1.1 on 2024-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='alt',
        ),
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
