# Generated by Django 5.1.1 on 2024-10-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_rename_task_image_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='task.task'),
        ),
    ]
