# Generated by Django 5.1.1 on 2024-10-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metatitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
